name: Create Webp

on:
  push:
    branches:
      - master  # Set a branch to deploy

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Compress
        id: Compress
        uses: zhixuan666/Compress-Picture-Action@master

      - uses: EndBug/add-and-commit@v6 # You can change this to use a specific version
        with:
          # The message for the commit
          # Default: 'Commit from GitHub Actions (name of the workflow)'
          message: 'Create by zhixuan666/Compress-Picture-Action'

          # Token to use for pushing the commit. The default value won't trigger any workflows, you need to use a Personal Access Token for that.
          # Default: secrets.GITHUB_TOKEN
          token: ${{ secrets.GITHUB_TOKEN }}